// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oid85.FinMarket.Momentum.Infrastructure.Database;

#nullable disable

namespace Oid85.FinMarket.Momentum.Infrastructure.Migrations
{
    [DbContext(typeof(MomentumContext))]
    [Migration("20260912074353_12092026_2")]
    partial class _12092026_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Oid85.FinMarket.Momentum.Infrastructure.Database.Entities.ParameterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParameterEntities", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.Momentum.Infrastructure.Database.Entities.StrategyExecuteResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AnnualYieldReturn")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<double>("EndMoney")
                        .HasColumnType("double precision");

                    b.Property<string>("EquityCurve")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaxDrawdown")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxDrawdownPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("NetProfit")
                        .HasColumnType("double precision");

                    b.Property<double>("RecoveryFactor")
                        .HasColumnType("double precision");

                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<double>("StartMoney")
                        .HasColumnType("double precision");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyParams")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tickers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalReturn")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("StrategyExecuteResultEntities", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
